# Programming in TensorFlow 2.0

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.0.0-beta1'

In [ ]:
# pip install tensorflow-gpu==2.0.0-beta1

## Working with Tensors

A **tensor** is a generalization of vectors and matrices to potentially higher dimensions. TensorFlow represents tensors as n-dimensional arrays of base datatypes. Constants are a popular tensor type. https://www.tensorflow.org/guide/tensors

### Defining a tensor/constant

In [3]:
tensor = tf.constant([[1, 2], [4, 8]])

In [4]:
tensor

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 8]], dtype=int32)>

### Getting the shape of a tensor

In [5]:
tensor.shape

TensorShape([2, 2])

### Accessing values from constants

In [6]:
tensor.numpy() # No session needed

array([[1, 2],
       [4, 8]], dtype=int32)

### Defining constants from numpy arrays

In [7]:
numpy_array = np.array([[12, 44], [32.2, 1]])

In [8]:
numpy_to_tensor = tf.constant(numpy_array)

In [9]:
numpy_to_tensor

<tf.Tensor: id=3, shape=(2, 2), dtype=float64, numpy=
array([[12. , 44. ],
       [32.2,  1. ]])>

### Computations with tensors

In [10]:
tensor

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 8]], dtype=int32)>

### Tensors and scalars

In [11]:
tensor + 5

<tf.Tensor: id=7, shape=(2, 2), dtype=int32, numpy=
array([[ 6,  7],
       [ 9, 13]], dtype=int32)>

In [12]:
tensor * 2

<tf.Tensor: id=10, shape=(2, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 8, 16]], dtype=int32)>

### Tensors and Numpy functions

In [13]:
np.square(tensor)

array([[ 1,  4],
       [16, 64]], dtype=int32)

In [14]:
np.dot(tensor, numpy_to_tensor)

array([[ 76.4,  46. ],
       [305.6, 184. ]])

### Assigning Values to Tensors

Constant don't have an assign function. We have to use variables for this task. A TensorFlow **variable** is the best way to represent shared, persistent state manipulated by your program. https://www.tensorflow.org/guide/variables



In [15]:
tensor[0,0].assign(100) # does not work because tensor is a constant.

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [16]:
tensor_variable = tf.Variable(tensor)

In [17]:
tensor_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [4, 8]], dtype=int32)>

In [18]:
tensor_variable[0,0].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[100,   2],
       [  4,   8]], dtype=int32)>

In [19]:
tensor_variable # updated value

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[100,   2],
       [  4,   8]], dtype=int32)>

In [20]:
tensor # not modified

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 8]], dtype=int32)>

## Building Machine Learning Models

In [21]:
model = tf.keras.models.Sequential([
    
    # Adds a densely-connected layer with 6 units to the model:
    tf.keras.layers.Dense(6, activation = 'linear', input_shape = [8]),
    tf.keras.layers.Dense(6, activation = 'relu'),
    tf.keras.layers.Dense(4, activation = 'softmax')
    
])

![](network.png)

In [22]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 54        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 28        
Total params: 124
Trainable params: 124
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(train_features, train_labels, epochs=10)